services:
  rosbridge:
    image: ros:humble
    command: >
      bash -c "
        apt update &&
        apt install -y ros-humble-rosbridge-server ros-humble-rmw-cyclonedds-cpp &&
        ros2 launch rosbridge_server rosbridge_websocket_launch.xml
      "
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host

  # --- Dummy publishers for local dev ---
  dummies:
    image: ros:humble
    volumes:
      - ./ros_dummies:/ros_dummies
    command: >
      bash -c "
        apt update &&
        apt install -y ros-humble-rmw-cyclonedds-cpp &&
        export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp &&
        python3 /ros_dummies/diagnostic_heartbeat.py &
        python3 /ros_dummies/bool_beacon.py &
        python3 /ros_dummies/navsat_circle.py &
        python3 /ros_dummies/odom_circle.py
      "
    environment:
      - ROS_DOMAIN_ID=0
#      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp 
# Set this manually in the command only after the installation of cyclonedds
    network_mode: host

  # --- React dev server (hot-reload) ---
  ui:
    build: ./ui
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    network_mode: host
    depends_on:
      - rosbridge
    environment:
      - VITE_ROSBRIDGE_URL=ws://localhost:9090
