services:
  backend:
    build: ./server
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - /home/${USER}/navigation:/navigation
      - /var/run/docker.sock:/var/run/docker.sock # hopefully TEMPORARY fix
      # this docker.sock is necessary so that the backend can call ros2 commands
      # to be executed in the rosbridge container to speed up prototyping by 
      # not using the non-working roslibjs for the action clients
      # roslibjs would be better, maybe rclnodejs but this would also require
      # modifications to the robot to provide more action clients
    environment:
      - ROSBRIDGE_URL=ws://localhost:9090
    network_mode: host
    depends_on:
      - rosbridge
  rosbridge:
    image: ros:jazzy
    volumes:
      - /home/${USER}/navigation:/navigation
    command: >
      bash -c "
        apt update &&
        apt install -y ros-jazzy-rosbridge-server ros-jazzy-rmw-cyclonedds-cpp ros-jazzy-nav2-msgs &&
        ros2 launch rosbridge_server rosbridge_websocket_launch.xml
      "
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host
  # --- React dev server (hot-reload) ---
  ui:
    build: ./ui
    volumes:
      - ./ui:/app
      - ./config:/app/config
      - ./data:/app/data
    command: sh -c "npm install && npm run dev -- --host"
    network_mode: host
    depends_on:
      - rosbridge
    environment:
      - VITE_BACKEND_URL=ws://localhost:8080
      - VITE_API_URL=http://localhost:8080
